file ="./testFile/sqlFile/m_project_member"
f=open(file,"r")
# print(id(f))
# read_data=f.readlines()
print(f.readline())
print(f.readline())
# print("input"+f.read(2))
# print(id(f))
# print(f.readlines())
# print(id(f))
# print(read_data[0].replace("\n",""))
# print(read_data[1].replace("\n",""))
# print(f[1])
# print(f.readlines(0)[0].replace("\n",""))